# todo add another test for express for travis cli
sudo: required
services:
  - docker

before_install:
  - docker build -t ozkhan/client-test -f ./client/Dockerfile.dev ./client
  # todo add tests to server and worker

script:
  - docker run -e CI=true ozkhan/client-test npm test

after_sucess:
  - docker build -t ozkhan/multi-client ./client
  - docker build -t ozkhan/multi-nginx ./nginx
  - docker build -t ozkhan/multi-server ./server
  - docker build -t ozkhan/multi-worker ./worker

  # login into  dpocker cli
  # echo out docker password which is a env var then login with docker id n pass
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take the built images above and pass them to docker hub
  - docker push ozkhan/multi-client
  - docker push ozkhan/multi-nginx
  - docker push ozkhan/multi-server
  - docker push ozkhan/multi-worker
