# todo add another test for express for travis cli
sudo: required
services:
  - docker

before_install:
  - docker build -t ozkhan/client-test -f ./client/Dockerfile.dev ./client
  # todo add tests to server and worker

script:
  # - docker run ozkhan/client-test npm test -- --coverage
  - docker run -e CI=true ozkhan/client-test npm test

after_success:
  - docker build -t ozkhan/multi-client ./client
  - docker build -t ozkhan/multi-nginx ./nginx
  - docker build -t ozkhan/multi-server ./server
  - docker build -t ozkhan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ozkhan/multi-client #multi client did not push to docker?>??
  - docker push ozkhan/multi-nginx
  - docker push ozkhan/multi-server
  - docker push ozkhan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "mult-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-415095052881"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
